/* eslint-disable no-useless-assignment */
/**
 * tavernHelperExporter.ts — Export card as a complete Tavern Helper project structure
 * Generates a self-contained project that can be deployed via jsdelivr CDN
 *
 * References:
 * - enterprise20020924-web/- : tavern_sync.yaml, webpack bundling
 * - # 前端项目改造指南.md : Frontend project restructure guide
 */

import type { CharacterCardV3 } from '../../types/card.types';
import type { MVUZODSchema, MVUZODField } from '../../types/mvuzod.types';

// ─── Types ──────────────────────────────────────────────────────────────

export interface ExportResult {
  files: ExportFile[];
  totalSize: number;
  warnings: string[];
}

export interface ExportFile {
  path: string;
  content: string;
  type: 'ts' | 'html' | 'yaml' | 'json' | 'css';
  description: string;
}

// ─── Main Export Function ───────────────────────────────────────────────

export function exportAsTavernHelper(
  card: CharacterCardV3,
  schema: MVUZODSchema | null,
  options: { projectName?: string; cdnOwner?: string; cdnRepo?: string } = {},
): ExportResult {
  const files: ExportFile[] = [];
  const warnings: string[] = [];

  const projectName = options.projectName || card.data.name?.replace(/\s+/g, '_') || 'tavern_project';
  const cdnOwner = options.cdnOwner || 'YOUR_GITHUB_USERNAME';
  const cdnRepo = options.cdnRepo || projectName;

  // 1. Generate Zod Schema Script
  if (schema) {
    files.push({
      path: 'dist/variables/schema.ts',
      content: generateZodSchemaFile(schema, card.data.name),
      type: 'ts',
      description: 'Zod schema definition for MVU ZOD framework',
    });

    // 2. Generate InitVar entry
    files.push({
      path: 'dist/variables/initvar.ts',
      content: generateInitVarFile(schema),
      type: 'ts',
      description: 'Initial variable values',
    });
  } else {
    warnings.push('No MVUZOD schema found. Schema files not generated.');
  }

  // 3. Generate main index.ts
  files.push({
    path: 'dist/index.ts',
    content: generateIndexFile(projectName, !!schema),
    type: 'ts',
    description: 'Main entry point',
  });

  // 4. Generate index.html
  files.push({
    path: 'dist/index.html',
    content: generateIndexHtml(projectName, card.data.name),
    type: 'html',
    description: 'HTML entry for Tavern Helper',
  });

  // 5. Generate tavern_sync.yaml
  files.push({
    path: 'tavern_sync.yaml',
    content: generateSyncYaml(cdnOwner, cdnRepo, files.map(f => f.path)),
    type: 'yaml',
    description: 'CI/CD auto-update configuration',
  });

  // 6. Generate styles.css
  files.push({
    path: 'dist/styles.css',
    content: generateStyles(projectName),
    type: 'css',
    description: 'Scoped CSS styles',
  });

  // 7. Generate card JSON
  files.push({
    path: `${projectName}.json`,
    content: JSON.stringify(card, null, 2),
    type: 'json',
    description: 'Character Card V3 JSON export',
  });

  const totalSize = files.reduce((sum, f) => sum + f.content.length, 0);

  return { files, totalSize, warnings };
}

// ─── File Generators ────────────────────────────────────────────────────

function generateZodSchemaFile(schema: MVUZODSchema, charName: string): string {
  const lines: string[] = [
    "// Auto-generated by Tavern Card Studio",
    `// Character: ${charName}`,
    `// Generated: ${new Date().toISOString()}`,
    "",
    "import { registerMvuSchema } from 'https://testingcf.jsdelivr.net/gh/StageDog/tavern_resource/dist/util/mvu_zod.js';",
    "",
    "export const Schema = z.object({",
  ];

  function renderField(field: MVUZODField, indent: number): string[] {
    const pad = '  '.repeat(indent);
    const name = field.path.split('/').filter(Boolean).pop() ?? field.path;
    const result: string[] = [];

    if (field.children?.length) {
      result.push(`${pad}'${name}': z.object({`);
      for (const child of field.children) {
        result.push(...renderField(child, indent + 1));
      }
      result.push(`${pad}}).prefault({}),`);
    } else {
      let zodType = '';
      switch (field.type) {
        case 'number':
          zodType = field.constraints?.coerce ? 'z.coerce.number()' : 'z.number()';
          if (field.constraints?.clamp) {
            zodType += `.transform(v => _.clamp(v, ${field.constraints?.clamp[0]}, ${field.constraints?.clamp[1]}))`;
          }
          break;
        case 'string':
          zodType = 'z.string()';
          break;
        case 'boolean':
          zodType = 'z.boolean()';
          break;
        case 'record':
          zodType = 'z.record(z.string(), z.string())';
          break;
        case 'array':
          zodType = 'z.array(z.string())';
          break;
        default:
          zodType = 'z.unknown()';
      }
      if (field.constraints?.prefault !== undefined) {
        zodType += `.prefault(${JSON.stringify(field.constraints?.prefault)})`;
      }
      if (field.description) {
        zodType += `.describe('${field.description.replace(/'/g, "\\'")}')`;
      }
      result.push(`${pad}'${name}': ${zodType},`);
    }
    return result;
  }

  for (const field of schema.fields) {
    lines.push(...renderField(field, 1));
  }

  lines.push('}).prefault({});');
  lines.push('');
  lines.push('$(() => {');
  lines.push('  registerMvuSchema(Schema);');
  lines.push('});');

  return lines.join('\n');
}

function generateInitVarFile(schema: MVUZODSchema): string {
  function buildDefault(fields: MVUZODField[]): Record<string, unknown> {
    const obj: Record<string, unknown> = {};
    for (const f of fields) {
      const name = f.path.split('/').filter(Boolean).pop() ?? f.path;
      if (f.children?.length) {
        obj[name] = buildDefault(f.children);
      } else {
        obj[name] = f.defaultValue ?? getTypeDefault(f.type);
      }
    }
    return obj;
  }

  const defaults = buildDefault(schema.fields);

  return [
    '// Auto-generated InitVar by Tavern Card Studio',
    '// Edit these values to change initial game state',
    '',
    `export const INITIAL_STATE = ${JSON.stringify(defaults, null, 2)};`,
    '',
    '// To use in worldbook entry:',
    '// Comment: [InitVar]Khởi tạo biến',
    '// Content: The JSON above',
    '// Settings: constant=true, position=before_char, scan_depth=0',
  ].join('\n');
}

function generateIndexFile(projectName: string, hasSchema: boolean): string {
  return [
    `// ${projectName} — Main Entry`,
    '// Auto-generated by Tavern Card Studio',
    '',
    hasSchema ? "import './variables/schema';" : '// No schema defined',
    '',
    '// Event listeners',
    "on('message_received', (msg) => {",
    '  console.log(`[${projectName}] Message received:`, msg.message_id);',
    '  // Handle incoming messages...',
    '});',
    '',
    "on('mvu_state_changed', (newState) => {",
    `  console.log('[${projectName}] State changed:', newState);`,
    '  // Update UI based on new state...',
    '});',
    '',
    `console.log('[${projectName}] Loaded successfully');`,
  ].join('\n');
}

function generateIndexHtml(projectName: string, charName: string): string {
  return `<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${charName} — ${projectName}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="app" class="${projectName}-root">
    <!-- Game UI will be rendered here -->
    <div class="loading">Loading ${charName}...</div>
  </div>
  <script type="module" src="index.ts"></script>
</body>
</html>`;
}

function generateSyncYaml(owner: string, repo: string, filePaths: string[]): string {
  return [
    '# Tavern Card Studio — Auto-sync configuration',
    '# This file configures jsdelivr CDN auto-update',
    '',
    'update_strategy: jsdelivr',
    `jsdelivr_base: "https://testingcf.jsdelivr.net/gh/${owner}/${repo}"`,
    '',
    'files:',
    ...filePaths.filter(p => p.startsWith('dist/')).map(p => `  - ${p}`),
    '',
    '# GitHub Actions will auto-build and push to jsdelivr',
    '# See: https://github.com/StageDog/tavern_helper_template',
  ].join('\n');
}

function generateStyles(projectName: string): string {
  return `/* ${projectName} — Scoped styles */
/* Auto-generated by Tavern Card Studio */

.${projectName}-root {
  font-family: 'Noto Sans', 'Noto Sans TC', sans-serif;
  color: #e0e0e0;
  line-height: 1.6;
}

.${projectName}-root .loading {
  text-align: center;
  padding: 40px;
  color: #8b8fa3;
  font-size: 14px;
}

/* Status bar */
.${projectName}-root .status-bar {
  display: flex;
  gap: 12px;
  padding: 8px 12px;
  background: rgba(0,0,0,0.2);
  border-radius: 8px;
  margin-bottom: 12px;
}

.${projectName}-root .stat-item {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
}

.${projectName}-root .stat-bar {
  width: 60px;
  height: 4px;
  background: rgba(255,255,255,0.1);
  border-radius: 2px;
  overflow: hidden;
}

.${projectName}-root .stat-bar-fill {
  height: 100%;
  background: linear-gradient(90deg, #667eea, #764ba2);
  border-radius: 2px;
  transition: width 0.3s ease;
}
`;
}

function getTypeDefault(type: string): unknown {
  switch (type) {
    case 'number': return 0;
    case 'boolean': return false;
    case 'string': return '';
    case 'array': return [];
    case 'record': return {};
    case 'object': return {};
    default: return null;
  }
}

// ─── jsdelivr Linker ────────────────────────────────────────────────────

export function generateJsdelivrLinks(
  owner: string,
  repo: string,
  files: string[],
  branch = 'main',
): Array<{ file: string; url: string; scriptTag: string }> {
  return files.map(file => {
    const url = `https://testingcf.jsdelivr.net/gh/${owner}/${repo}@${branch}/${file}`;
    const ext = file.split('.').pop();
    let scriptTag: string;

    if (ext === 'js' || ext === 'ts') {
      scriptTag = `<script type="module" src="${url}"></script>`;
    } else if (ext === 'css') {
      scriptTag = `<link rel="stylesheet" href="${url}">`;
    } else {
      scriptTag = `<!-- ${url} -->`;
    }

    return { file, url, scriptTag };
  });
}

export function generateAutoLoaderScript(
  owner: string,
  repo: string,
  branch = 'main',
): string {
  return `<!-- Tavern Card Studio Auto-Loader -->
<!-- Paste this into your card's HTML/body section -->
<body>
<script>
(async () => {
  const base = 'https://testingcf.jsdelivr.net/gh/${owner}/${repo}@${branch}/dist';
  
  // Load CSS
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = \`\${base}/styles.css\`;
  document.head.appendChild(link);
  
  // Load main script
  const script = document.createElement('script');
  script.type = 'module';
  script.src = \`\${base}/index.ts\`;
  document.body.appendChild(script);
})();
</script>
</body>`;
}

